import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Content from '../components/Content';
export default function Home() {
  return (
    <div>
      <Head>
        <title>AapkaStore</title>
        <meta name="description" content="Generated by  create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/aslogo.ico" />
        {/* always use lazyload */}
        {/* <script src='/sc.js'></script> */}
      </Head>
     <Content/>
    </div>
  )
}
